export const dataPets=[
    {
        name:'Sima',
        img:'https://images.pexels.com/photos/1805164/pexels-photo-1805164.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
        dayStart :'2021-03-16',
        dayEnd :'2021-03-20',
        comment:'calm kind dog',
        contact:'Victor',
        phone:'+123456789',
        pet:'dog',
    },
    {
        name:'Lessy',
        img:'https://images.pexels.com/photos/2820134/pexels-photo-2820134.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
        dayStart :'2021-03-16',
        dayEnd :'2021-03-20',
        comment:' affectionate, playful',
        contact:'Diana',
        phone:'+123456789',
        pet:'dog',
    },
    {
        name:'Murka',
        img:'https://images.pexels.com/photos/45201/kitty-cat-kitten-pet-45201.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
        dayStart :'2021-03-16',
        dayEnd :'2021-03-20',
        comment:'affectionate kitten, litter box, does not scratch furniture',
        contact:'Anna',
        phone:'+123456789',
        pet:'cat',
    },
    {
        name:'Sharlota',
        img:'https://images.pexels.com/photos/991831/pexels-photo-991831.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
        dayStart :'2021-03-16',
        dayEnd :'2021-03-20',
        comment:'',
        contact:'Irina',
        phone:'+123456789',
        pet:'cat',
    },
    {
        name:'Tosha',
        img:'https://images.pexels.com/photos/1661179/pexels-photo-1661179.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
        dayStart :'2021-03-16',
        dayEnd :'2021-03-20',
        comment:'vociferous',
        contact:'Victor',
        phone:'+123456789',
        pet:'parrot',
    },
    {
      name:'Sharlota',
      img:'https://images.pexels.com/photos/991831/pexels-photo-991831.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      dayStart :'2021-03-16',
      dayEnd :'2021-03-20',
      comment:'',
      contact:'Irina',
      phone:'+123456789',
      pet:'cat',
    },
    {
        name:'Chack',
        img:'https://images.pexels.com/photos/97082/weimaraner-puppy-dog-snout-97082.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
        dayStart :'2021-03-16',
        dayEnd :'2021-03-20',
        comment:'labrador, affectionate, playful',
        contact:'Diana',
        phone:'+123456789',
        pet:'dog',
    },
    {
        name:'Gosha',
        img:'https://images.pexels.com/photos/2540644/pexels-photo-2540644.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
        dayStart :'2021-03-16',
        dayEnd :'2021-03-20',
        comment:'affectionate kitten, litter box, does not scratch furniture',
        contact:'Anna',
        phone:'+123456789',
        pet:'parrot',
    },
]



export const dataSiters = [
    {
        name: 'Artur',
        raitingPos: '10',
        raitingNeg: '0',
        reviews: 'reviews(2)',
        offer: "I'll take a dog or a cat",
        adress: 'Sovetskay str.',
        phone: '123456789',
        pict:null
    },
    {
        name: 'Lera',
        raitingPos: '2',
        raitingNeg: '0',
        reviews: 'reviews(2)',
        offer: "I'll take a bird",
        adress: 'Sovetskay str.',
        phone: '123456789',
        pict:null
    },
    {
        name: 'Olga',
        raitingPos: '0',
        raitingNeg: '1',
        reviews: 'reviews(2)',
        offer: "I will accept any pet",
        adress: 'Sovetskay str.',
        phone: '123456789',
        pict:null
    },
    {
        name: 'Irina',
        raitingPos: '10',
        raitingNeg: '0',
        reviews: 'reviews(2)',
        offer: "I'll take a dog or a cat",
        adress: 'Sovetskay str.',
        phone: '123456789',
        pict:null
    },
    {
        name: 'Natalia',
        raitingPos: '12',
        raitingNeg: '0',
        reviews: 'reviews(2)',
        offer: "I'll take a dog or a cat",
        adress: 'Sovetskay str.',
        phone: '123456789',
        pict:null
    },
    {
        name: 'Vadim',
        raitingPos: '3',
        raitingNeg: '0',
        reviews: 'reviews(3)',
        offer: "I'll take a dog or a cat",
        adress: 'Sovetskay str.',
        phone: '123456789',
        pict:null
    },
]
